name: Build & Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build React App
      - name: Build Webpack App
        run: |
          npm install
          npm run build
          tar -czf react-app.tar.gz -C dist .

      # Upload Build Archive to VPS
      - name: Upload React App Archive
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "react-app.tar.gz"
          target: ${{ secrets.VPS_TARGET_DIR }}

      # Clean Old Build and Extract New on VPS
      - name: Extract and Deploy React App on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd "${{ secrets.VPS_TARGET_DIR }}"

            echo "Cleaning old React build artifacts..."
            find . \
              -type f \
              \( -name "*.js" -o -name "*.js.map" -o -name "*.gz" -o -name "*.chunk.js" \) \
              -not -name "index.html" \
              -not -name ".htaccess" \
              -delete

            echo "Extracting new build..."
            tar -xzf react-app.tar.gz
            rm react-app.tar.gz
            echo "React app deployed successfully."
